SIMDB/Models/Movie.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;
using SIMDB.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SIMDB.Models
{
    public class Movie
    {
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [Display(Name = "Movie")]
        [Required(ErrorMessage = "Movie Title is required")]
        public string title { get; set; }

        [Display(Name = "Director")]
        [Required(ErrorMessage = "Name at least one director")]
        public string director { get; set; }

        [Display(Name = "Cast")]
        [Required(ErrorMessage = "Name at least one cast member")]
        public string actors { get; set; }

        [Display(Name = "Cover")]
        [Required(ErrorMessage = "Enter any image link to the movie cover")]
        [ImageMustBeLink(ErrorMessage = "Cover must be a link to an image!")]
        public string image { get; set; }

        [Display(Name = "Year")]
        [Required(ErrorMessage = "Year is required")]
        [Range(0, 2021, ErrorMessage = "You can only travel in time in movies")]
        public int year { get; set; }

        public UpdateDefinition<Movie> GetUpdateAllDefinitionForMovie()
        {
            return Builders<Movie>.Update
                .Set(x => x.title, title)
                .Set(x => x.director, director)
                .Set(x => x.actors, actors)
                .Set(x => x.image, image)
                .Set(x => x.year, year);
        }
    }
}

SIMDB/Models/MoviesDB.cs
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace SIMDB.Models
{
    public class MoviesDB
    {
        // Our web.config contains the Database name and Connectionstring 
        public string ConnectionString = ConfigurationManager.AppSettings["ConnectionString"];
        public string DatabaseName = ConfigurationManager.AppSettings["DatabaseName"];

        // Representing our database (movie)
        public IMongoDatabase Database;

        public MoviesDB()
        {
            var client = new MongoClient(ConnectionString);
            Database = client.GetDatabase(DatabaseName);
        }

        // Predefine our table of Movies in a MongoCollection
        public IMongoCollection<Movie> Movies
        {
            get
            {
                var movies = Database.GetCollection<Movie>("movie");

                return movies;
            }
        }
    }
}

SIMDB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIMDB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SIMDB/Controllers/MoviesController.cs
using MongoDB.Bson;
using MongoDB.Driver;
using SIMDB.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIMDB.Controllers
{
    public class MoviesController : Controller
    {
        // Database Context
        private readonly MoviesDB dbContext = new MoviesDB();

        // GET: Movies
        public ActionResult Index()
        {
            var movies = dbContext.Movies.Find(new BsonDocument()).ToList();

            return View(movies);
        }

        // GET: Movie
        public ActionResult Details(Movie movie)
        {
            var selectedMovie = dbContext.Movies.Find(Builders<Movie>.Filter.Eq("Id", movie.Id)).FirstOrDefault();

            return View(selectedMovie);
        }

        // Init a Movie creation Form
        public ActionResult Create()
        {
            return View();
        }

        // POST: Insert the new movie into DB
        [HttpPost]
        public ActionResult Create(Movie newMovie)
        {
            if(ModelState.IsValid)
            {
                dbContext.Movies.InsertOneAsync(newMovie);

                return RedirectToAction("Details", newMovie);
            }

            return View(newMovie);
        }

        [HttpGet]
        public ActionResult Edit(Movie movie)
        {
            if (movie.Id == null)
                return RedirectToAction("Index");

            var movieToEdit = dbContext.Movies.Find(x => x.Id == movie.Id).FirstOrDefault();

            return View(movieToEdit);
        }

        // POST: Update our edited Movie.
        // Note: added seperator because Edit GET also has to return the movie object (string returns null)
        //       otherwise the functions are identical and the controller does not like that.
        //       Not a great practise, but the string vs object problem could be specific to Mongo.
        [HttpPost]
        public ActionResult Edit(Movie movie, int? seperator = null)
        {
            if(ModelState.IsValid)
            {
                dbContext.Movies.UpdateOne(Builders<Movie>.Filter.Where(x => x.Id == movie.Id), movie.GetUpdateAllDefinitionForMovie());

                return RedirectToAction("Details", movie);
            }

            return RedirectToAction("Edit");           
        }

        [HttpGet]
        public ActionResult Delete(Movie movie)
        {
            if (movie.Id == null)
                return RedirectToAction("Index");

            var movieToDelete = dbContext.Movies.Find(Builders<Movie>.Filter.Eq("Id", movie.Id)).FirstOrDefault();

            return View(movieToDelete);
        }

        [HttpPost]
        public ActionResult Delete(Movie movie, int? seperator = null)
        {
            if (movie.Id == null)
                return RedirectToAction("Index");

            var movieDelete = dbContext.Movies.DeleteOne(Builders<Movie>.Filter.Where(x => x.Id == movie.Id));

            return RedirectToAction("Index");
        }
    }
}

SIMDB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br/>
<div class="jumbotron">
    <h1>SIMDb</h1>
    <p class="lead">Simulating IMDb because it's fun!</p>
    <p>@Html.ActionLink("Movies you say?", "Index", "Movies", null, new { @class = "btn btn-success btn-lg" })</p>
    <p><a href="https://imdb.com" class="btn btn-primary btn-lg" target="_blank" rel="noopener noreferrer" >IMDb you say? &raquo;</a></p>
</div>

SIMDB/Views/Movies/Create.cshtml
@model SIMDB.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movies</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.actors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.actors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.actors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Movies", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIMDB/Views/Movies/Delete.cshtml
@model SIMDB.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img class="movie-images" src="@Html.DisplayFor(model => model.image)" alt="Image" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.year)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to Movies", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

SIMDB/Views/Movies/Details.cshtml
@model SIMDB.Models.Movie

@{
    ViewBag.Title = "Movie Details";
}

<h2>Details</h2>

<div>
    <h4>Movies</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img class="movie-images" src="@Html.DisplayFor(model => model.image)" alt="Image" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.year)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Back to Movies", "Index", null, new { @class = "btn btn-info" })
</p>

SIMDB/Views/Movies/Edit.cshtml
@model SIMDB.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movies</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.actors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.actors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.actors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Movies", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIMDB/Views/Movies/Index.cshtml
@model IEnumerable<SIMDB.Models.Movie>

@{
    ViewBag.Title = "Movies";
}

<h2>Movies</h2>

<p>
    @Html.ActionLink("Add Movie", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.director)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.actors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.year)
        </th>
        <th class="button-panel"></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.director)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.actors)
        </td>
        <td class="movie-column">
            <img class="movie-images" src="@Html.DisplayFor(modelItem => item.image)" alt="Image" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.year)
        </td>
        <td class="button-panel">
            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

SIMDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SIMDb", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SIMDb - Assignment for Trivident</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>